### PR TITLE
fix(CompositeDevice): Free force feedback effects on device remove

### LINKED ISSUE #255: GPD Win Mini: Rumble stops working after suspend
After suspend and resume, the rumble stops working. Here are the logs starting after resume:

```
Jan 18 13:25:37 chimeraos inputplumber[10421]: [2025-01-18T21:25:37Z INFO  inputplumber::input::manager] Found missing device, adding source device "evdev://event9" to existing composite device: "/org/shadowblip/InputPlumber/CompositeDevice0"
Jan 18 13:25:37 chimeraos inputplumber[10421]: [2025-01-18T21:25:37Z ERROR inputplumber::input::composite_device] Failed running device: "error occurred running device"
Jan 18 13:25:37 chimeraos inputplumber[10421]: [2025-01-18T21:25:37Z INFO  inputplumber::input::manager] Preparing for system resume
Jan 18 13:25:37 chimeraos inputplumber[10421]: [2025-01-18T21:25:37Z INFO  inputplumber::input::composite_device] Preparing for system resume for: /org/shadowblip/InputPlumber/CompositeDevice0
Jan 18 13:25:37 chimeraos inputplumber[10421]: [2025-01-18T21:25:37Z INFO  inputplumber::input::composite_device] Restoring target devices: ["touchpad", "xb360", "mouse", "keyboard"]
Jan 18 13:25:37 chimeraos inputplumber[10421]: [2025-01-18T21:25:37Z INFO  inputplumber::input::manager] Finished preparing for system resume
Jan 18 13:25:38 chimeraos inputplumber[10421]: [2025-01-18T21:25:38Z INFO  inputplumber::input::composite_device] Setting target devices: ["xb360", "keyboard", "mouse", "touchpad"]
```

### PR DESCRIPTION
**Pull request by justinweiss**
If a source device is removed and later added back, the force feedback effect map can get out of sync with the device state. The removed device's state needs to be deleted from the objects referencing it.

Fixes #255

### CODE REVIEW

File: src/input/composite_device/mod.rs [hunk 1]
```diff
@@ -1479,6 +1479,23 @@ impl CompositeDevice {
         let path = device.devnode();
         let id = device.get_id();
 
+        let mut freed_effect_ids = Vec::new();
```
Comment (pastaq) [inline src/input/composite_device/mod.rs:1482]: Add Comment
`// Remove any ffb effects this device registered`

File: src/input/composite_device/mod.rs [hunk 2]
```diff
@@ -1479,6 +1479,23 @@ impl CompositeDevice {
...
+
```
Comment (pastaq) [inline src/input/composite_device/mod.rs:1483]: Add Comment
`// Loop through all registered effects and remove this device as a source`

File: src/input/composite_device/mod.rs [hunk 3]
```diff
@@ -1479,6 +1479,23 @@ impl CompositeDevice {
...
+        for (effect_id, source_map) in self.ff_effect_id_source_map.iter_mut() {
+            if source_map.remove(&id).is_some() {
+                log::debug!("Removed source {id} from effect {effect_id}");
+            }
+            if source_map.is_empty() {
```
Comment (pastaq) [inline src/input/composite_device/mod.rs:1488]: Add Comment
`// If this was the last user of the effect, stage the effect for removal`

File: src/input/composite_device/mod.rs [hunk 4]
```diff
@@ -1479,6 +1479,23 @@ impl CompositeDevice {
...
+                freed_effect_ids.push(*effect_id);
+            }
+        }
+
+        for effect_id in freed_effect_ids {
```
Comment (pastaq) [inline src/input/composite_device/mod.rs:1493]: Add Comment
`// Remove all effects previously staged`

**Review by pastaq — CHANGES_REQUESTED** [review]
Looks good, just some a minor request for comments to add clarity.

**Review by pastaq — APPROVED** [review]
