### PR TITLE
fix: avoid inputs cancelling each other

### LINKED ISSUE #258: [Bug] Not possible to map same buttons to both D-Pad and analog stick
Currently, mapping a set of keys (say the arrow keys) to both the D-pad and an analog stick produces a broken config: 

- analog controls work
- d-pad only works for up and left but not down and right

From what I understand, this is due to how InputPlumber processes axis mappings. However, having both the d-pad and the left stick mapped to the same directions is very common in platformers, fighting games or shmups so it would be worthwhile to find a workaround for that use case.

### PR DESCRIPTION
**Pull request by imLinguin**
Closes #258

This is a proposition of a solution that addresses said issue. 
By mapping target_capability -> source_capability we can reference "ownership" of an input to given source event within the CompositeDevice. I think this change should be considered potentially breaking.

At the moment this prevents input cancellation for buttons on Gamepad, Keyboard and Mouse capabilities

### CODE REVIEW

File: src/input/composite_device/mod.rs [hunk 1]
```diff
@@ -831,9 +838,46 @@ impl CompositeDevice {
...
+                                    e.remove();
+                                }
+                                Some(event)
+                            } else {
+                                None
+                            }
+                        }
+                    }
+                })
+                .collect()
```
Comment (ShadowApex) [inline src/input/composite_device/mod.rs:880]: I can foresee us filtering other kinds of events in the future, so I think it would be good to break this out into its own function:

```rust

    /// Filter out input-cancelling events that do not come from same
    /// capability as the initiator
    fn filter_event(&mut self, event: NativeEvent) -> Option<NativeEvent> {
        let Some(src_cap) = event.get_source_capability() else {
            return Some(event);
        };
        let tgt_cap = event.as_capability();

        // Handle only button presses
        if !matches!(
            tgt_cap,
            Capability::Gamepad(Gamepad::Button(_))
                | Capability::Keyboard(_)
                | Capability::Mouse(Mouse::Button(_))
        ) {
            return Some(event);
        }
        let pressed = event.pressed();
        match self.exclusive_inputs.entry(tgt_cap) {
            Entry::Vacant(e) => {
                if pressed {
                    e.insert(src_cap.clone());
                }
                Some(event)
            }
            Entry::Occupied(e) => {
                if e.get() == &src_cap {
                    if !pressed {
                        e.remove();
                    }
                    Some(event)
                } else {
                    None
                }
            }
        }
    }
```

Then that also simplifies the `handle_event` logic:

```rust
        ...
        
        // Translate the event using the device profile.
        let mut events = if self.device_profile.is_some() {
            self.translate_event(&event)
                .await?
                .into_iter()
                .filter_map(|event| self.filter_event(event))
                .collect()
        } else {
            vec![event]
        };
        
        ...
```

**Review by ShadowApex — CHANGES_REQUESTED** [review]
I think this is a good change. Thanks for this! I just had one comment, but otherwise looks good!

**Review by ShadowApex — APPROVED** [review]
Looks good! Thank you!

File: src/input/composite_device/mod.rs [hunk 2]
```diff
@@ -153,6 +156,9 @@ pub struct CompositeDevice {
     /// List of currently active buttons and keys. Used to block "up" events for
     /// keys that have already been handled.
     active_inputs: Vec<Capability>,
+    /// Mapping of target and source capabilities preventing input release events
+    /// coming from capabilities that didn't start the event
```
Comment (pastaq) [inline src/input/composite_device/mod.rs:160]: Small nit, can you more clearly define in the comment what the key/value pattern is. As they are both Capability it might become confusing to understand if the target or source capability is the key or the value.

Comment (imLinguin) [reply src/input/composite_device/mod.rs]: Sure thing. Let me know if this change covers it well enough

**Review by pastaq — APPROVED** [review]
